# Generated by Django 4.1.6 on 2023-03-11 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='unique_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
