# Generated by Django 4.1.6 on 2023-03-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_productcategorie_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Группа категорий товаров',
                'verbose_name_plural': 'Группы категорий товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productcuisine'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_categories',
            field=models.ManyToManyField(blank=True, to='main.groupproductcategory'),
        ),
    ]
