# Generated by Django 4.1.6 on 2023-03-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_groupproductcategory_productcuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productcuisine'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.groupproductcategory'),
        ),
    ]
