# Generated by Django 4.1.6 on 2023-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
