# Generated by Django 4.1.6 on 2023-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_productcategory_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='groupproductcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
