FROM node:19-alpine

WORKDIR /app

COPY ./foodinflight_frontend/package.json /app/package.json
RUN npm install --omit=dev

COPY ./foodinflight_frontend /app
RUN npm run build
CMD cp -r /app/build/. /app/build1
