FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV INSIDE_A_DOCKER Yes

COPY ./bot/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./.env /app/
RUN chmod +x /app/main.py

CMD ["python", "/app/main.py"]
