FROM node:19-alpine

WORKDIR /app

COPY ./foodinflight_frontend/package*.json ./
RUN npm install --omit=dev

COPY ./foodinflight_frontend ./
RUN npm run build --production
RUN npm install -g serve
CMD serve -s build
